[2025-04-24T15:50:09.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T15:50:09.919+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_lab.check_latest_date manual__2025-04-24T15:49:58.614971+00:00 [queued]>
[2025-04-24T15:50:10.007+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_lab.check_latest_date manual__2025-04-24T15:49:58.614971+00:00 [queued]>
[2025-04-24T15:50:10.009+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T15:50:10.437+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): check_latest_date> on 2025-04-24 15:49:58.614971+00:00
[2025-04-24T15:50:10.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_lab', 'check_latest_date', 'manual__2025-04-24T15:49:58.614971+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp669l7v9g']
[2025-04-24T15:50:10.488+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1921) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-24T15:50:10.501+0000] {standard_task_runner.py:72} INFO - Started process 1929 to run task
[2025-04-24T15:50:10.501+0000] {standard_task_runner.py:105} INFO - Job 138: Subtask check_latest_date
[2025-04-24T15:50:10.998+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_lab.check_latest_date manual__2025-04-24T15:49:58.614971+00:00 [running]> on host 7ce975cba66d
[2025-04-24T15:50:12.894+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_lab' AIRFLOW_CTX_TASK_ID='check_latest_date' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T15:49:58.614971+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T15:49:58.614971+00:00'
[2025-04-24T15:50:12.914+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T15:50:12.962+0000] {logging_mixin.py:190} INFO - Checking latest date in Snowflake table: TB_SYMPTOMS_GGSHEET
[2025-04-24T15:50:15.252+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-04-24T15:50:16.524+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.2, Python Version: 3.12.6, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-24T15:50:20.889+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T15:50:22.012+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T15:50:28.359+0000] {job.py:229} INFO - Heartbeat recovered after 19.83 seconds
[2025-04-24T15:50:29.020+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T15:50:29.021+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T15:50:29.032+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T15:50:29.033+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_lab, task_id=check_latest_date, run_id=manual__2025-04-24T15:49:58.614971+00:00, execution_date=20250424T154958, start_date=20250424T155009, end_date=20250424T155029
[2025-04-24T15:50:29.052+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T15:50:29.068+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-24T15:50:29.068+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
