[2025-04-24T14:47:44.366+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T14:47:44.374+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-24T14:47:33.913776+00:00 [queued]>
[2025-04-24T14:47:44.378+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-24T14:47:33.913776+00:00 [queued]>
[2025-04-24T14:47:44.378+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T14:47:44.384+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_snowflake> on 2025-04-24 14:47:33.913776+00:00
[2025-04-24T14:47:44.387+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-24T14:47:44.388+0000] {standard_task_runner.py:72} INFO - Started process 189 to run task
[2025-04-24T14:47:44.389+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_lab', 'load_data_to_snowflake', 'manual__2025-04-24T14:47:33.913776+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmptp_624oq']
[2025-04-24T14:47:44.389+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask load_data_to_snowflake
[2025-04-24T14:47:44.412+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-24T14:47:33.913776+00:00 [running]> on host 7ce975cba66d
[2025-04-24T14:47:44.454+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_lab' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T14:47:33.913776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T14:47:33.913776+00:00'
[2025-04-24T14:47:44.456+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T14:47:44.457+0000] {logging_mixin.py:190} INFO - No new data to load into Snowflake.
[2025-04-24T14:47:44.457+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T14:47:44.462+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T14:47:44.462+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_lab, task_id=load_data_to_snowflake, run_id=manual__2025-04-24T14:47:33.913776+00:00, execution_date=20250424T144733, start_date=20250424T144744, end_date=20250424T144744
[2025-04-24T14:47:44.489+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T14:47:44.497+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T14:47:44.498+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
